[terminal]
vt = 1

[default_session]
command = "tuigreet --cmd /bin/sh --theme border=lightred;text=white;prompt=purple;time=orange;action=green;button=LightGray;container=black;input=white"
user = "greeter"

[initial_session]
user = "darsh"